worldPackage: pinball_maze
environment:
  moduleName: pinball_maze_environment
  configDict:
    DRAG: 0.995
    NOISE:
        MU_POS: [0.0, 0.0]
        MU_VEL: [0.0, 0.0]
        SIGMA: 0.0
    END_EPISODE_REWARD: 10000
    MAZE: pinball_simple_single.cfg
    STEP_PENALTY: -1
    SUBSTEPS: 20
    THRUST_PENALTY: -1
agent:
  moduleName: td_lambda_agent
  configDict:
    stateDimensionResolution: {"x": 15, "y": 15, "xdot": 3, "ydot": 3}
    epsilon: 0.1
    epsilonDecay: 1.0
    function_approximator:
      default: 0.0
      learning_rate: 0.2
      name: CMAC
      number_of_tilings: 10
    gamma: 0.9999
    lambda: 0.99
    minTraceValue: 0.1
    replacingTraces: true
    update_rule: SARSA
monitor:
    plotObservables : ['greedypolicy']
    policyLogFrequency : 100
    stateActionValuesLogging:
        active : True
        logFrequency : 10
        stateDims: ["x", "y"]
        actions : None
        rasterPoints : 50
    functionOverStateSpaceLogging:
        active : True
        logFrequency : 10
        stateDims : ["x", "y"]
        rasterPoints : 50

