worldPackage : maze_cliff
environment:
    moduleName : "maze_cliff_environment"
    configDict: 
       cliffPenalty : -100
       stochasticity : 0.0
agent:
    moduleName : "td_lambda_agent"
    configDict:
        update_rule : "SARSA"
        epsilon : 0.01
        epsilonDecay : 1.0
        gamma : 1.0
        lambda : 0.0
        minTraceValue : 0.5
        function_approximator :  
            name: 'TabularStorage'
            default: 0.0
            learning_rate : 1.0
monitor:
    policyLogFrequency : 1000
